version: '3.8'
services:

  nginx:
    container_name: nginx
    image: nginx:1.25.5-alpine
    ports:
      - "8080:80"
    volumes:
      - ${PWD}/nginx:/etc/nginx/conf.d
      - ${PWD}/workspace:/var/www/html
    depends_on:
      - php
    links:
      - php
    networks:
      - app-network

  php:
    container_name: php
    image: legalone/php-fpm
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - app-network

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.16.2
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "9200:9200"
    volumes:
      - ${PWD}/esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl http://elasticsearch:9200" ]
      interval: 10s
      timeout: 10s
      retries: 120
    restart: always
    networks:
      - app-network

  logstash:
    container_name: logstash
    image: logstash:7.16.2
    volumes:
      - ${PWD}/logstash/config:/usr/share/logstash/config
      - ${PWD}/logstash/logs.log:/tmp/logs.log
    ports:
      - "5044:5044"
    command: logstash -f /usr/share/logstash/config/logstash.conf
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - app-network

volumes:
  esdata: {}

networks:
  app-network:
    driver: bridge
